apiVersion: apps/v1
kind: Deployment
metadata:
  name: newname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newname
  template:
    metadata:
      labels:
        app: newname
    spec:
      containers:
      - image: okteto.dev/newname:latest
        name: newname
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "7876fc80-ee26-4e7f-9d30-5241034aafac"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "7876fc80-ee26-4e7f-9d30-5241034aafac"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/Share233"
